data_wrangle1 <- mjdf %>% group_by(STATE) %>% summarise(COMPUTERS.MATH.AND.STATS = mean(COMPUTERS.MATH.AND.STATS), BIOLOGY.AND.AGRICULTURE = mean(BIOLOGY.AND.AGRICULTURE), PHYSICS = mean(PHYSICS), PSYCHOLOGY = mean(PSYCHOLOGY), SOCIOLOGY = mean(SOCIOLOGY), ENGINEERING = mean(ENGINEERING), MULTIDISCIPLINARY.STUDIES = mean(MULTIDISCIPLINARY.STUDIES), SCIENCES = mean(SCIENCES), BUSINESS = mean(BUSINESS), EDUCATION = mean(EDUCATION), LITERATURE.AND.LANGUAGES = mean(LITERATURE.AND.LANGUAGES), LIBERAL.ARTS.AND.HISTORY = mean(LIBERAL.ARTS.AND.HISTORY), VISUAL.AND.PERFORMING.ARTS = mean(VISUAL.AND.PERFORMING.ARTS), COMMUNICATION = mean(COMMUNICATION), OTHER = mean(OTHER))


tidy_wrangle1 <- gather(data_wrangle1, Degree, 'STATE')
names(tidy_wrangle1) <- c("State", "Degree", "Percentage")

states <- c('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'KS', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY')

l <- list()
for (i in states) {
  newdata <- subset(tidy_wrangle1, State == i)
  p <- ggplot(newdata, aes(x=Degree, y=Percentage)) + geom_bar(stat='identity') +ggtitle(i) + coord_flip()
  print(p)
  l[[i]] <- p
}

png("C:\\workspace\\DataVisualization\\DV_RProject3\\00 Doc\\data_wrangle_vis1.png", width = 25, height = 50, units = "in", res = 150)
grid.newpage()
pushViewport(viewport(layout = grid.layout(10, 25)))   

print(l[[1]], vp = viewport(layout.pos.row = 1, layout.pos.col = 1:5))
print(l[[2]], vp = viewport(layout.pos.row = 1, layout.pos.col = 6:10))
print(l[[3]], vp = viewport(layout.pos.row = 1, layout.pos.col = 11:15))
print(l[[4]], vp = viewport(layout.pos.row = 1, layout.pos.col = 16:20))
print(l[[5]], vp = viewport(layout.pos.row = 1, layout.pos.col = 21:25))
print(l[[6]], vp = viewport(layout.pos.row = 2, layout.pos.col = 1:5))
print(l[[7]], vp = viewport(layout.pos.row = 2, layout.pos.col = 6:10))
print(l[[8]], vp = viewport(layout.pos.row = 2, layout.pos.col = 11:15))
print(l[[9]], vp = viewport(layout.pos.row = 2, layout.pos.col = 16:20))
print(l[[10]], vp = viewport(layout.pos.row = 2, layout.pos.col = 21:25))
print(l[[11]], vp = viewport(layout.pos.row = 3, layout.pos.col = 1:5))
print(l[[12]], vp = viewport(layout.pos.row = 3, layout.pos.col = 6:10))
print(l[[13]], vp = viewport(layout.pos.row = 3, layout.pos.col = 11:15))
print(l[[14]], vp = viewport(layout.pos.row = 3, layout.pos.col = 16:20))
print(l[[15]], vp = viewport(layout.pos.row = 3, layout.pos.col = 21:25))
print(l[[16]], vp = viewport(layout.pos.row = 4, layout.pos.col = 1:5))
print(l[[17]], vp = viewport(layout.pos.row = 4, layout.pos.col = 6:10))
print(l[[18]], vp = viewport(layout.pos.row = 4, layout.pos.col = 11:15))
print(l[[19]], vp = viewport(layout.pos.row = 4, layout.pos.col = 16:20))
print(l[[20]], vp = viewport(layout.pos.row = 4, layout.pos.col = 21:25))
print(l[[21]], vp = viewport(layout.pos.row = 5, layout.pos.col = 1:5))
print(l[[22]], vp = viewport(layout.pos.row = 5, layout.pos.col = 6:10))
print(l[[23]], vp = viewport(layout.pos.row = 5, layout.pos.col = 11:15))
print(l[[24]], vp = viewport(layout.pos.row = 5, layout.pos.col = 16:20))
print(l[[25]], vp = viewport(layout.pos.row = 5, layout.pos.col = 21:25))
print(l[[26]], vp = viewport(layout.pos.row = 6, layout.pos.col = 1:5))
print(l[[27]], vp = viewport(layout.pos.row = 6, layout.pos.col = 6:10))
print(l[[28]], vp = viewport(layout.pos.row = 6, layout.pos.col = 11:15))
print(l[[29]], vp = viewport(layout.pos.row = 6, layout.pos.col = 16:20))
print(l[[30]], vp = viewport(layout.pos.row = 6, layout.pos.col = 21:25))
print(l[[31]], vp = viewport(layout.pos.row = 7, layout.pos.col = 1:5))
print(l[[32]], vp = viewport(layout.pos.row = 7, layout.pos.col = 6:10))
print(l[[33]], vp = viewport(layout.pos.row = 7, layout.pos.col = 11:15))
print(l[[34]], vp = viewport(layout.pos.row = 7, layout.pos.col = 16:20))
print(l[[35]], vp = viewport(layout.pos.row = 7, layout.pos.col = 21:25))
print(l[[36]], vp = viewport(layout.pos.row = 8, layout.pos.col = 1:5))
print(l[[37]], vp = viewport(layout.pos.row = 8, layout.pos.col = 6:10))
print(l[[38]], vp = viewport(layout.pos.row = 8, layout.pos.col = 11:15))
print(l[[39]], vp = viewport(layout.pos.row = 8, layout.pos.col = 16:20))
print(l[[40]], vp = viewport(layout.pos.row = 8, layout.pos.col = 21:25))
print(l[[41]], vp = viewport(layout.pos.row = 9, layout.pos.col = 1:5))
print(l[[42]], vp = viewport(layout.pos.row = 9, layout.pos.col = 6:10))
print(l[[43]], vp = viewport(layout.pos.row = 9, layout.pos.col = 11:15))
print(l[[44]], vp = viewport(layout.pos.row = 9, layout.pos.col = 16:20))
print(l[[45]], vp = viewport(layout.pos.row = 9, layout.pos.col = 21:25))
print(l[[46]], vp = viewport(layout.pos.row = 10, layout.pos.col = 1:5))
print(l[[47]], vp = viewport(layout.pos.row = 10, layout.pos.col = 6:10))
print(l[[48]], vp = viewport(layout.pos.row = 10, layout.pos.col = 11:15))
print(l[[49]], vp = viewport(layout.pos.row = 10, layout.pos.col = 16:20))


dev.off()
